[project]
name = "classy"
dynamic=["version"]
requires-python = ">=3.12"
description="Python interface to the Cosmological Boltzmann code CLASS"
authors = [
  {name = "Julien Lesgourgues"},
  {name = "Thomas Tram"},
  {name = "Nils Schöneberg"},
  {name = "... and many more (see webpage)"}
]
dependencies = [
    "anesthetic>=2.14.4",
    "arviz>=1.0.0",
    "cobaya>=3.6.2",
    "corner>=2.2.3",
    "iminuit>=2.32.0",
    "mpi4py>=4.1.1",
    "ptmcmcsampler>=2.1.4",
]

[project.urls]
Homepage = "http://www.class-code.net"
# Documentation = https://readthdocs.org/classy # TBD

[build-system]
requires = ['setuptools','wheel','numpy','cython']
build-backend = "setuptools.build_meta"
